# Supprimer l'événement maximize pour toutes les fenêtres

# Opacité pour Kitty
windowrule = opacity 0.9 0.9, match:class ^(kitty)$
windowrule = opacity 0.80 0.80 0.80, match:class .*

windowrule = opacity 0.20 0.20 0.20, match:class ^(wofi)$
